### ISSUE TITLE
Here are a few comments and some typos that I noticed

### ISSUE THREAD

**Issue by Macxim** [ManzDev/roadmap-web-developer-2017#1]
### Comments

- Regarding accessibility, what about [ARIA](https://developer.mozilla.org/es/docs/Web/Accessibility/ARIA) attributes?
- About search engines in SEO, what about DuckDuckGo and Yahoo? 
- Nothing about DevTools or debugging ?
- Technically PostCSS is not really a preprocessor but a postprocessor (like for example Autoprefixer, that seems to be missing by the way).
- Technically React is not a framework but a library.
- Nothing about [Prepack](https://prepack.io/). Might be too soon, though.
- Unless I'm talking nonsense, it seems to me that Codekit is not package manager but rather a tool like Prepros (compiler, live-reload, optimization, etc.) 

### Typos
- Javascript --> JavaScript
- SASS --> [Sass](http://sassnotsass.com/)
- Optimizators --> Optimization tools 
- Typographic & Icons --> Typography & Icons
- Prepos --> Prepros (?) (It's much more than just a browser reload app)
- CoffeScript --> CoffeeScript

I think that's it for now.  
Like I said on Facebook, it would be cool if the chart would be a bit more interactive, with link(s) for each item.

**Comment by ManzDev** [comment]
My opinions:

- ARIA attributes: Ok, added.
- [Yahoo redirect to Bing results](https://search.yahoo.com/info/submit.html): Discard.
- [Duck Duck Go discard sitemap & webmaster tools](https://duck.co/forum/thread/4099/ddg-webmaster-tools-sitemap-submissions): Discard.
- DevTools or Debugging: Yes. I want add "Performance" section. I think in "DevOps". Opinions?
- PostCSS: Right, but I want simplify roadmap (no more tools in same section). Now, autoprefixer is a module inside PostCSS. Added.
- I think that Framework vs Library is a sensitive subject. Opinions?
- Prepack: Ok, added (In DevOps, I think).
- Right, I renamed Package Manager to Package/Tool Manager.

- Typos: Very thanks, fixed!
- Interactive roadmap: Maybe, soon!

If you disagree with something, please, comment.

**Comment by Macxim** [comment]
- I'm not sure the Development and debugging tools really belong in DevOps, they are (JS) Front-End skills, not DevOps skills.
- I think it's definitely too soon for Prepack (v0.2.1). Sorry for mentioning it.
- You're right about the Framework VS Library issue (it doesn't really matter that much, I guess)

**Comment by ManzDev** [comment]
I have to add a section of "Performance" (DevTools, Network performance, etc ...). I had thought that it would be ideal to include it inside DevOps because requires general knowledge (CDN, server optimization, database optimization, front-end optimization, etc...) 

Maybe create a dedicated profile just for optimization?

**Comment by Macxim** [comment]
👍 for a dedicated section for performance/optimization.
